modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/owmii/powah/issues"
license="LGPLv3"

[[mods]]
modId="powah"
version="${version}"
displayName="Powah"
displayURL="https://www.curseforge.com/minecraft/mc-mods/powah"
authors="owmii"
description='''
Various ways to generate, store and transmit FE power.
'''

[[dependencies.powah]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"
    ordering="NONE"
    side="BOTH"